In [5]:
import os
import numpy as np
import pandas as pd
import datetime
import cv2
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn.metrics import confusion_matrix, classification_report

import tensorflow as tf
from tensorflow.keras import layers, models, optimizers, callbacks

from tensorflow.keras.callbacks import ReduceLROnPlateau
from keras.preprocessing.image import ImageDataGenerator, load_img
from keras.layers import Conv2D, Dense, BatchNormalization, Activation, Dropout, MaxPooling2D, Flatten
from keras.optimizers import Adam
from keras import regularizers
from keras.callbacks import ModelCheckpoint, CSVLogger, TensorBoard, EarlyStopping
from keras.utils import plot_model

In [12]:
def get_images(directory):
    directory= directory.replace('.DS_Store', '')
    print(directory)
    Images = []
    Labels = []  
    for labels in os.listdir(directory): #Main Directory where each class label is present as folder name.
        print(labels)
        if labels=='.DS_Store':
            print(labels)
        else:
            for image_file in os.listdir(directory+labels): #Extracting the file name of the image from Class Label folder
                image = cv2.imread(directory+labels+r'/'+image_file) #Reading the image (OpenCV)
                image = cv2.resize(image,(224,224)) #Resize the image, Some images are different sizes. (Resizing is very Important)
                Images.append(image)
                Labels.append(labels)

    return shuffle(Images,Labels,random_state=817328462) #Shuffle the dataset you just prepared.



In [13]:
#Train data
test, test_label = get_images("//Users//pragatpagariya//Desktop//NCI//sem2//ML//project //archive (12)//train//") #Extract the training images from the folders.

test = np.array(test) #converting the list of images to numpy array.
test_label = np.array(test_label)

//Users//pragatpagariya//Desktop//NCI//sem2//ML//project //archive (12)//train//
happy
.DS_Store
.DS_Store
sad
fearful
neutral
angry
disgusted
surprised


In [14]:
test

array([[[[157, 157, 157],
         [157, 157, 157],
         [157, 157, 157],
         ...,
         [ 35,  35,  35],
         [ 32,  32,  32],
         [ 32,  32,  32]],

        [[157, 157, 157],
         [157, 157, 157],
         [157, 157, 157],
         ...,
         [ 34,  34,  34],
         [ 32,  32,  32],
         [ 32,  32,  32]],

        [[157, 157, 157],
         [157, 157, 157],
         [157, 157, 157],
         ...,
         [ 37,  37,  37],
         [ 34,  34,  34],
         [ 34,  34,  34]],

        ...,

        [[203, 203, 203],
         [203, 203, 203],
         [204, 204, 204],
         ...,
         [160, 160, 160],
         [160, 160, 160],
         [160, 160, 160]],

        [[204, 204, 204],
         [204, 204, 204],
         [205, 205, 205],
         ...,
         [160, 160, 160],
         [160, 160, 160],
         [160, 160, 160]],

        [[204, 204, 204],
         [204, 204, 204],
         [204, 204, 204],
         ...,
         [160, 160, 160],
        

In [15]:


# Example NumPy array
arr = np.array([test])

# Convert NumPy array to tuple
arr_tuple = tuple(arr)

# Now you can use arr_tuple as a key in dictionaries or sets


In [16]:
test

array([[[[157, 157, 157],
         [157, 157, 157],
         [157, 157, 157],
         ...,
         [ 35,  35,  35],
         [ 32,  32,  32],
         [ 32,  32,  32]],

        [[157, 157, 157],
         [157, 157, 157],
         [157, 157, 157],
         ...,
         [ 34,  34,  34],
         [ 32,  32,  32],
         [ 32,  32,  32]],

        [[157, 157, 157],
         [157, 157, 157],
         [157, 157, 157],
         ...,
         [ 37,  37,  37],
         [ 34,  34,  34],
         [ 34,  34,  34]],

        ...,

        [[203, 203, 203],
         [203, 203, 203],
         [204, 204, 204],
         ...,
         [160, 160, 160],
         [160, 160, 160],
         [160, 160, 160]],

        [[204, 204, 204],
         [204, 204, 204],
         [205, 205, 205],
         ...,
         [160, 160, 160],
         [160, 160, 160],
         [160, 160, 160]],

        [[204, 204, 204],
         [204, 204, 204],
         [204, 204, 204],
         ...,
         [160, 160, 160],
        

In [5]:
from collections import Counter
Counter(test_label)

Counter({'sad': 4830,
         'fearful': 4097,
         'neutral': 4965,
         'surprised': 3171,
         'angry': 3995,
         'happy': 7215,
         'disgusted': 436})

In [6]:
n_samples = len(test)
data_imagesRGB = test.reshape((n_samples, -1))

In [7]:
# Splitting dataset into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_imagesRGB, test_label, test_size=0.20, shuffle=True)

In [8]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [ ]:

from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(max_depth=300)
dt.fit(X_train,y_train)
yhat_classes = dt.predict(X_test)
print(classification_report(y_test, yhat_classes))
print(confusion_matrix(y_test, yhat_classes))


In [9]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7) 
knn.fit(X_train,y_train)
yhat_classes = knn.predict(X_test)
print(classification_report(y_test, yhat_classes))
print(confusion_matrix(y_test, yhat_classes))

              precision    recall  f1-score   support

       angry       0.25      0.22      0.23       836
   disgusted       0.22      0.25      0.24        91
     fearful       0.29      0.28      0.29       835
       happy       0.38      0.50      0.43      1426
     neutral       0.26      0.39      0.31       936
         sad       0.32      0.17      0.22       989
   surprised       0.53      0.30      0.38       629

    accuracy                           0.32      5742
   macro avg       0.32      0.30      0.30      5742
weighted avg       0.33      0.32      0.32      5742

[[180  11 101 237 195  88  24]
 [  7  23   9  24  20   3   5]
 [112  11 234 213 146  67  52]
 [119  24 133 715 300  96  39]
 [121  10  93 260 363  65  24]
 [119  15 143 275 249 165  23]
 [ 56   9  91 143 112  32 186]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier
print("RF")
rfc = RandomForestClassifier(n_estimators=300, max_depth=300)  
rfc.fit(X_train, y_train)
# calculate accuracy of class predictions
y_pred = rfc.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test, yhat_classes))

In [2]:
import torch
from transformers import ViTFeatureExtractor, ViTForImageClassification
from matplotlib.ticker import MaxNLocator
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches

# Loading pytorch packages.

import torch
from transformers import BertTokenizer, BertForSequenceClassification, AdamW, BertConfig, get_linear_schedule_with_warmup
from torch.utils.data import TensorDataset, random_split, DataLoader, RandomSampler, SequentialSampler
import random

import warnings
warnings.filterwarnings("ignore")

In [13]:
model = BertForSequenceClassification.from_pretrained(
    'bert-large-uncased', # Use the 124-layer, 1024-hidden, 16-heads, 340M parameters BERT model with an uncased vocab.
    num_labels = 2, # The number of output labels--2 for binary classification. You can increase this for multi-class tasks.   
    output_attentions = False, # Whether the model returns attentions weights.
    output_hidden_states = False, # Whether the model returns all hidden-states.
)

# Tell pytorch to run this model on the device which we set GPU in our case.

model.to(device)

Some weights of the model checkpoint at bert-large-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint a

NameError: name 'device' is not defined

In [3]:
feature_extractor = ViTFeatureExtractor.from_pretrained('google/vit-base-patch16-224-in21k')
model = ViTForImageClassification.from_pretrained('google/vit-base-patch16-224-in21k')

Some weights of the model checkpoint at google/vit-base-patch16-224-in21k were not used when initializing ViTForImageClassification: ['pooler.dense.weight', 'pooler.dense.bias']
- This IS expected if you are initializing ViTForImageClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ViTForImageClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224-in21k and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
image_tensors = torch.tensor(test.transpose(0, 3, 1, 2))  # Convert image arrays to PyTorch tensors

# Step 4: Perform inference using the pre-trained model
with torch.no_grad():
    outputs = model(pixel_values=image_tensors)  # Perform inference on the image tensors

# Step 5: Extract predictions
predictions = outputs.logits.softmax(dim=-1)  # Get softmax probabilities for each class
predicted_classes = torch.argmax(predictions, dim=-1)  # Get predicted class labels

# Step 6: Print predicted classes
print(predicted_classes)